#ifndef LINKEDLIST_SHORTCUT_H
#define LINKEDLIST_SHORTCUT_H

#include "linkedlist_functions.h"

typedef g_2_linkedlist_s_t g_linkedlist_s_t;
typedef g_2_linkedlist_s_node_t g_linkedlist_s_node_t;

#define g_linkedlist_s_new g_2_linkedlist_s_new
#define g_linkedlist_s_init g_2_linkedlist_s_init
#define g_linkedlist_s_push g_2_linkedlist_s_push
#define g_linkedlist_s_unshift g_2_linkedlist_s_unshift
#define g_linkedlist_s_shift g_2_linkedlist_s_shift
#define g_linkedlist_s_push_node g_2_linkedlist_s_push_node
#define g_linkedlist_s_unshift_node g_2_linkedlist_s_unshift_node
#define g_linkedlist_s_shift_node g_2_linkedlist_s_shift_node
#define g_linkedlist_s_node_new g_2_linkedlist_s_node_new
#define g_linkedlist_s_node_get_addr g_2_linkedlist_s_node_get_addr
#define g_linkedlist_s_node_dispose g_2_linkedlist_s_node_dispose
#define g_linkedlist_s_insert_after g_2_linkedlist_s_insert_after
#define g_linkedlist_s_insert_node_after g_2_linkedlist_s_insert_node_after
#define g_linkedlist_s_remove_after g_2_linkedlist_s_remove_after
#define g_linkedlist_s_remove_node_after g_2_linkedlist_s_remove_node_after
#define g_linkedlist_s_move_all_after g_2_linkedlist_s_move_all_after
#define g_linkedlist_s_move_all_after_node g_2_linkedlist_s_move_all_after_node
#define g_linkedlist_s_deinit g_2_linkedlist_s_deinit
#define g_linkedlist_s_dispose g_2_linkedlist_s_dispose

#endif
